<?php

return [

    /* ------------------------------------------------------------------ */
    /* Shared / common                                                      */
    /* ------------------------------------------------------------------ */
    'hub_title'         => 'Reports',
    'hub_description'   => 'Permission-aware reporting across all UHMS modules.',
    'generated_by'      => 'Generated by',
    'generated_at'      => 'Generated at',
    'date_from'         => 'Date From',
    'date_to'           => 'Date To',
    'date'              => 'Date',
    'department'        => 'Department',
    'all_departments'   => 'All Departments',
    'user_staff'        => 'User / Staff',
    'all_staff'         => 'All Staff',
    'status'            => 'Status',
    'all_statuses'      => 'All Statuses',
    'payment_method'    => 'Payment Method',
    'all_methods'       => 'All Methods',
    'provider'          => 'Provider',
    'all_providers'     => 'All Providers',
    'doctor'            => 'Doctor',
    'all_doctors'       => 'All Doctors',
    'blood_group'       => 'Blood Group',
    'all_groups'        => 'All Groups',
    'run'               => 'Run',
    'clear'             => 'Clear',
    'filter'            => 'Filter',
    'export_csv'        => 'Export CSV',
    'export_excel'      => 'Export Excel',
    'export_pdf'        => 'Export PDF',
    'print'             => 'Print',
    'refresh_dashboard' => 'Refresh Dashboard',
    'no_data'           => 'No data matches this report.',
    'no_records'        => 'No records found.',
    'total_rows'        => 'Total Rows',
    'total'             => 'Total',
    'subtotal'          => 'Subtotal',
    'grand_total'       => 'Grand Total',
    'view_report'       => 'View Report',
    'reports_dashboard' => 'Reports Dashboard',
    'search'            => 'Search',

    /* ------------------------------------------------------------------ */
    /* Generic column headings (used in table/CSV headers)                  */
    /* ------------------------------------------------------------------ */
    'col_date'          => 'Date',
    'col_visit'         => 'Visit',
    'col_patient'       => 'Patient',
    'col_department'    => 'Department',
    'col_status'        => 'Status',
    'col_doctor'        => 'Doctor',
    'col_services'      => 'Services',
    'col_started'       => 'Started',
    'col_completed'     => 'Completed',
    'col_icd_code'      => 'ICD Code',
    'col_diagnosis'     => 'Diagnosis',
    'col_type'          => 'Type',
    'col_primary'       => 'Primary',
    'col_entered_by'    => 'Entered By',
    'col_complaint'     => 'Complaint',
    'col_duration'      => 'Duration',
    'col_severity'      => 'Severity',
    'col_dispensed_at'  => 'Dispensed At',
    'col_prescription'  => 'Prescription',
    'col_medication'    => 'Medication',
    'col_quantity'      => 'Quantity',
    'col_dispensed_by'  => 'Dispensed By',
    'col_request'       => 'Request',
    'col_urgency'       => 'Urgency',
    'col_items'         => 'Items',
    'col_requested_by'  => 'Requested By',
    'col_service'       => 'Service',
    'col_priority'      => 'Priority',
    'col_emergency_no'  => 'Emergency #',
    'col_arrival'       => 'Arrival',
    'col_triage'        => 'Triage',
    'col_disposition'   => 'Disposition',
    'col_bay'           => 'Bay',
    'col_team'          => 'Team',
    'col_admission_no'  => 'Admission #',
    'col_ward_bed'      => 'Ward / Bed',
    'col_admission_date'=> 'Admission Date',
    'col_los'           => 'Length Of Stay',
    'col_admitted_by'   => 'Admitted By',
    'col_discharged'    => 'Discharged',
    'col_location'      => 'Location',
    'col_reason'        => 'Reason / Reaction',
    'col_dose'          => 'Dose',
    'col_nurse'         => 'Nurse',
    'col_invoice'       => 'Invoice',
    'col_billing_type'  => 'Billing Type',
    'col_total'         => 'Total',
    'col_paid'          => 'Paid',
    'col_balance'       => 'Balance',
    'col_claim'         => 'Claim',
    'col_claim_type'    => 'Type',
    'col_claim_amount'  => 'Claim Amount',
    'col_item'          => 'Item',
    'col_direction'     => 'Direction',
    'col_batch'         => 'Batch',
    'col_expiry'        => 'Expiry',
    'col_performed_by'  => 'Performed By',
    'col_blood_group'   => 'Blood Group',
    'col_units'         => 'Units',
    'col_collected_at'  => 'Collected At',
    'col_issued_to'     => 'Issued To',
    'col_issued_by'     => 'Issued By',

    /* ------------------------------------------------------------------ */
    /* Section headings (report hub groups)                                */
    /* ------------------------------------------------------------------ */
    'sections' => [
        'management'    => 'Management Overview',
        'clinical'      => 'Clinical Reports',
        'patients'      => 'Patient / Visit Reports',
        'emergency'     => 'Emergency Reports',
        'admissions'    => 'Admission / Ward Reports',
        'pharmacy'      => 'Pharmacy Reports',
        'investigations'=> 'Investigation Reports',
        'theatre'       => 'Theatre / Procedure Reports',
        'billing'       => 'Billing Reports',
        'claims'        => 'Insurance / Claims Reports',
        'accounting'    => 'Accounting Reports',
        'receivables'   => 'Receivables Reports',
        'payables'      => 'Payables Reports',
        'stock'         => 'Stock / Procurement Reports',
        'hr'            => 'HR Reports',
        'audit'         => 'Audit Logs',
    ],

    /* ------------------------------------------------------------------ */
    /* Management                                                           */
    /* ------------------------------------------------------------------ */
    'management' => [
        'title'       => 'Management Overview',
        'description' => 'Hospital-wide activity, financial position, and risk summary.',
        'financial_summary'  => 'Financial Summary',
        'rendering_risk'     => 'Rendering Risk',
        'report_catalogue'   => 'Report Catalogue',
        'billed'             => 'Billed',
        'collected'          => 'Collected',
        'outstanding'        => 'Outstanding',
        'claims_total'       => 'Claims Total',
        'billed_not_rendered'=> 'Billed Not Rendered',
        'rendered_unpaid'    => 'Rendered Unpaid',
        'open_service_rendering_reports' => 'Open Service Rendering Reports',
    ],

    /* ------------------------------------------------------------------ */
    /* Clinical / operational catalogue                                    */
    /* ------------------------------------------------------------------ */
    'consultations' => [
        'title'       => 'Consultation Report',
        'description' => 'Department sessions, doctors, linked services, and session statuses.',
        'sessions'    => 'Sessions',
        'doctor'      => 'Doctor',
        'department'  => 'Department',
        'service'     => 'Service',
    ],
    'diagnoses' => [
        'title'       => 'Diagnosis Report',
        'description' => 'Clinical diagnoses by visit, department, doctor, ICD code, and type.',
        'icd_code'    => 'ICD Code',
        'diagnosis'   => 'Diagnosis',
        'type'        => 'Type',
    ],
    'complaints' => [
        'title'       => 'Complaints Report',
        'description' => 'Complaints and presenting history captured during clinical care.',
    ],

    /* ------------------------------------------------------------------ */
    /* Patients / Visits                                                    */
    /* ------------------------------------------------------------------ */
    'patients' => [
        'title'             => 'Patient Report',
        'description'       => 'Registered patients, demographics, and registration activity.',
        'total_patients'    => 'Total Patients',
        'new_patients'      => 'New Patients',
        'gender_breakdown'  => 'Gender Breakdown',
        'patient_number'    => 'Patient No.',
        'name'              => 'Name',
        'gender'            => 'Gender',
        'age'               => 'Age',
        'phone'             => 'Phone',
        'registered'        => 'Registered',
    ],
    'visits' => [
        'title'             => 'Visit Report',
        'description'       => 'Outpatient visits by type, department, doctor, and status.',
        'total_visits'      => 'Total Visits',
        'visit_number'      => 'Visit No.',
        'visit_type'        => 'Visit Type',
        'all_types'         => 'All Types',
        'department'        => 'Department',
        'doctor'            => 'Doctor',
        'visit_date'        => 'Visit Date',
    ],

    /* ------------------------------------------------------------------ */
    /* Emergency                                                            */
    /* ------------------------------------------------------------------ */
    'emergency' => [
        'title'             => 'Emergency Report',
        'description'       => 'Emergency attendance, triage, disposition, and operational status.',
        'total_cases'       => 'Total Cases',
        'active_cases'      => 'Active Cases',
        'triage_breakdown'  => 'Triage Breakdown',
        'disposition'       => 'Disposition',
        'case_number'       => 'Case No.',
        'triage_category'   => 'Triage Category',
        'arrival_time'      => 'Arrival Time',
    ],

    /* ------------------------------------------------------------------ */
    /* Admissions                                                           */
    /* ------------------------------------------------------------------ */
    'admissions' => [
        'title'              => 'Admission Register',
        'description'        => 'Inpatient admissions, ward/bed, length of stay, and discharge status.',
        'total_admissions'   => 'Total Admissions',
        'current_admissions' => 'Current Admissions',
        'discharges'         => 'Discharges',
        'avg_los'            => 'Avg. Length of Stay',
        'admission_date'     => 'Admission Date',
        'ward'               => 'Ward',
        'bed'                => 'Bed',
        'discharge_date'     => 'Discharge Date',
        'los_days'           => 'LOS (days)',
        'discharge_title'    => 'Discharge Register',
        'discharge_description' => 'Patient discharges, length of stay, and ward activity.',
    ],
    'mar' => [
        'title'       => 'MAR Report',
        'description' => 'Medication administration, overdue tasks, missed/held/refused doses, and nurse activity.',
        'administered'=> 'Administered',
        'overdue'     => 'Overdue',
        'missed'      => 'Missed',
        'refused'     => 'Refused',
    ],

    /* ------------------------------------------------------------------ */
    /* Pharmacy                                                             */
    /* ------------------------------------------------------------------ */
    'pharmacy' => [
        'title'              => 'Pharmacy Report',
        'description'        => 'Prescriptions, dispensing activity, and supplied quantities.',
        'sales_title'        => 'Pharmacy Sales Report',
        'sales_description'  => 'Drug sales, dispensing quantities, and revenue by drug/period.',
        'summary_title'      => 'Pharmacy Sales Summary',
        'summary_description'=> 'Drug sales summarised by product across a date range.',
        'total_sales'        => 'Total Sales',
        'total_qty'          => 'Total Qty',
        'drug'               => 'Drug',
        'qty_dispensed'      => 'Qty Dispensed',
        'unit_price'         => 'Unit Price',
        'total_amount'       => 'Total Amount',
        'prescription_no'    => 'Rx No.',
    ],

    /* ------------------------------------------------------------------ */
    /* Investigations / Lab                                                 */
    /* ------------------------------------------------------------------ */
    'investigations' => [
        'title'            => 'Investigation Report',
        'description'      => 'Requests, target departments, urgency, and result workflow status.',
        'revenue_title'    => 'Investigation Revenue Report',
        'revenue_description' => 'Revenue generated from investigation/lab services.',
        'total_requests'   => 'Total Requests',
        'pending'          => 'Pending',
        'in_progress'      => 'In Progress',
        'completed'        => 'Completed',
        'urgent'           => 'Urgent',
        'request_no'       => 'Request No.',
        'test'             => 'Test',
        'urgency'          => 'Urgency',
        'requested_by'     => 'Requested By',
        'result_status'    => 'Result Status',
    ],

    /* ------------------------------------------------------------------ */
    /* Theatre / Procedures                                                 */
    /* ------------------------------------------------------------------ */
    'procedures' => [
        'title'       => 'Procedure Report',
        'description' => 'Procedure requests, billing, acceptance, scheduling, and completion state.',
    ],
    'theatre' => [
        'title'       => 'Theatre Report',
        'description' => 'Theatre/procedure workload and operative workflow status.',
        'scheduled'   => 'Scheduled',
        'in_theatre'  => 'In Theatre',
        'completed'   => 'Completed',
        'cancelled'   => 'Cancelled',
    ],

    /* ------------------------------------------------------------------ */
    /* Billing                                                              */
    /* ------------------------------------------------------------------ */
    'billing' => [
        'title'              => 'Billing Report',
        'description'        => 'Invoices, payments, outstanding balances, and billed-not-rendered risk.',
        'daily_collections'  => 'Daily Collections',
        'daily_collections_description' => 'All payments received on a given date, by method and cashier.',
        'invoice_register'   => 'Invoice Register',
        'income_title'       => 'Income Report',
        'income_description' => 'Revenue collected by payment method over a date range.',
        'total_collected'    => 'Total Collected',
        'transactions'       => 'Transactions',
        'payment_methods'    => 'Payment Methods',
        'collection_by_method' => 'Collection by Payment Method',
        'receipt_no'         => 'Receipt No.',
        'time'               => 'Time',
        'invoice_no'         => 'Invoice No.',
        'method'             => 'Method',
        'received_by'        => 'Received By',
        'amount'             => 'Amount',
        'billed'             => 'Billed',
        'paid'               => 'Paid',
        'balance'            => 'Balance',
        'discount_title'     => 'Discount Report',
        'discount_description'=> 'Approved and pending discounts on invoices.',
        'ar_aging_title'     => 'AR Aging',
        'ar_aging_description'=> 'Accounts receivable ageing by bucket.',
        'aging_current'      => 'Current',
        'aging_0_30'         => '0–30 days',
        'aging_31_60'        => '31–60 days',
        'aging_61_90'        => '61–90 days',
        'aging_91_120'       => '91–120 days',
        'aging_120_plus'     => '120+ days',
        'create_invoice'     => 'Create Invoice',
    ],

    /* ------------------------------------------------------------------ */
    /* Claims / Insurance                                                   */
    /* ------------------------------------------------------------------ */
    'claims' => [
        'title'             => 'Claims Report',
        'description'       => 'Insurance claims by workflow, provider, status, and financial outcome.',
        'total_claims'      => 'Total Claims',
        'approved'          => 'Approved',
        'rejected'          => 'Rejected',
        'submitted'         => 'Submitted',
        'claim_no'          => 'Claim No.',
        'provider'          => 'Provider',
        'claim_amount'      => 'Claim Amount',
        'approved_amount'   => 'Approved Amount',
        'claim_date'        => 'Claim Date',
    ],

    /* ------------------------------------------------------------------ */
    /* Accounting                                                           */
    /* ------------------------------------------------------------------ */
    'accounting' => [
        'title'              => 'Accounting Reports',
        'description'        => 'Financial statements, ledger, journals, and posting integrity.',
        'trial_balance'      => 'Trial Balance',
        'general_ledger'     => 'General Ledger',
        'profit_loss'        => 'Profit & Loss',
        'balance_sheet'      => 'Balance Sheet',
        'cashbook'           => 'Cashbook',
        'failed_postings'    => 'Failed Accounting Postings',
        'revenue_by_dept'    => 'Revenue by Department',
        'expense_by_dept'    => 'Expense by Department',
    ],

    /* ------------------------------------------------------------------ */
    /* Receivables                                                          */
    /* ------------------------------------------------------------------ */
    'receivables' => [
        'title'       => 'Receivables Reports',
        'description' => 'AR aging, patient and insurance receivables, overdue balances.',
        'ar_aging'    => 'AR Aging',
        'patient_ar'  => 'Patient Receivables',
        'insurance_ar'=> 'Insurance Receivables',
        'sponsor_ar'  => 'Sponsor Receivables',
    ],

    /* ------------------------------------------------------------------ */
    /* Payables                                                             */
    /* ------------------------------------------------------------------ */
    'payables' => [
        'title'          => 'Payables Reports',
        'description'    => 'AP aging, supplier balances and payments.',
        'ap_aging'       => 'AP Aging',
        'supplier_stmt'  => 'Supplier Statement',
        'supplier_payments'=> 'Supplier Payments',
    ],

    /* ------------------------------------------------------------------ */
    /* Stock                                                                */
    /* ------------------------------------------------------------------ */
    'stock' => [
        'title'              => 'Stock Report',
        'description'        => 'Product stock movement and expiry-sensitive inventory activity.',
        'stock_valuation'    => 'Stock Valuation',
        'stock_valuation_description' => 'Current inventory value by location and product.',
        'expired_stock'      => 'Expired / Damaged Stock',
        'expired_description'=> 'Products past expiry or marked as damaged.',
        'total_value'        => 'Total Value',
        'product'            => 'Product',
        'location'           => 'Location',
        'qty_on_hand'        => 'Qty On Hand',
        'unit_cost'          => 'Unit Cost',
        'total_cost'         => 'Total Cost',
        'expiry_date'        => 'Expiry Date',
        'batch'              => 'Batch',
        'type'               => 'Type',
        'all_types'          => 'All Types',
    ],

    /* ------------------------------------------------------------------ */
    /* HR                                                                   */
    /* ------------------------------------------------------------------ */
    'hr' => [
        'leave_title'        => 'Leave Report',
        'leave_description'  => 'Leave requests by type, status, and staff member.',
        'payroll_title'      => 'Payroll Report',
        'payroll_description'=> 'Payroll records by period and approval status.',
        'leave_type'         => 'Leave Type',
        'all_leave_types'    => 'All Types',
        'pay_period'         => 'Pay Period',
        'staff'              => 'Staff',
        'days'               => 'Days',
        'net_pay'            => 'Net Pay',
    ],

    /* ------------------------------------------------------------------ */
    /* Blood Bank                                                           */
    /* ------------------------------------------------------------------ */
    'blood_bank' => [
        'title'       => 'Blood Bank Report',
        'description' => 'Blood inventory, requests, issue, transfusion, expiry, and wastage.',
    ],

    /* ------------------------------------------------------------------ */
    /* Audit                                                                */
    /* ------------------------------------------------------------------ */
    'audit' => [
        'title'       => 'Activity Log Report',
        'description' => 'User actions, high-risk events, and system activity.',
    ],

    /* ------------------------------------------------------------------ */
    /* Patient statement                                                    */
    /* ------------------------------------------------------------------ */
    'statement' => [
        'title'          => 'Patient Statement',
        'description'    => 'Financial statement for a patient across a date range.',
        'search_title'   => 'Patient Statement Search',
        'search_prompt'  => 'Search for a patient to generate their statement.',
        'search_placeholder' => 'Patient name or number...',
    ],
];
