<?php
return [
 'title'=>'Visit Financial Clearances','empty'=>'No financial clearance records found.',
 'status'=>['pending'=>'Pending','cleared'=>'Cleared','conditionally_cleared'=>'Conditionally cleared','financially_closed'=>'Financially closed','stale'=>'Stale'],
 'basis'=>['fully_settled'=>'Fully settled','zero_patient_responsibility'=>'Zero patient responsibility','fully_insured'=>'Fully insured','fully_sponsored'=>'Fully sponsored','corporate_guarantee'=>'Corporate guarantee','insurance_pending_approved'=>'Insurance pending approval','approved_outstanding_balance'=>'Approved outstanding balance','approved_payment_plan'=>'Approved payment plan','management_approval'=>'Management approval'],
 'exception_type'=>['outstanding_balance_approval'=>'Outstanding balance approval','payment_plan'=>'Payment plan','insurance_pending'=>'Insurance pending','corporate_guarantee'=>'Corporate guarantee','management_approval'=>'Management approval'],
 'fields'=>['visit'=>'Visit','patient'=>'Patient','status'=>'Status','basis'=>'Basis','outstanding'=>'Patient outstanding','action_required'=>'Finance action required','reason'=>'Reason','exceptions'=>'Exceptions','type'=>'Type','amount'=>'Amount'],
 'actions'=>['report'=>'Report','export'=>'Export','filter'=>'Filter','assess'=>'Assess','close'=>'Financially Close Visit','request_exception'=>'Request conditional clearance','request'=>'Request','approve'=>'Approve','save'=>'Save','rollback'=>'Return to disabled'],
 'metrics'=>['pending'=>'Pending','cleared'=>'Cleared','conditional'=>'Conditionally cleared','closed'=>'Financially closed','stale'=>'Stale','outstanding'=>'Outstanding patient balance'],
 'settings'=>['title'=>'Financial clearance settings','force_disabled'=>'The environment safety override is forcing financial clearance to disabled.','effective'=>'Effective mode','confirm_activation'=>'I confirm activation of financial closure'],
 'flash'=>['assessed'=>'Financial clearance assessed.','closed'=>'Visit financially closed.','reopened'=>'Financial clearance reopened.','exception_requested'=>'Exception requested.','exception_approved'=>'Exception approved.','settings_updated'=>'Settings updated.','rolled_back'=>'Financial clearance returned to disabled mode.'],
 'errors'=>['active_required'=>'Financial close is available only in active mode.','not_clear'=>'The visit is not financially clear.','pending_exists'=>'A pending exception already exists.','approved_exists'=>'A current approved exception already exists.','amount_exceeds_outstanding'=>'The amount must not exceed the live patient outstanding balance.','not_pending'=>'The exception is no longer pending.','self_approval'=>'The requester cannot approve their own exception.','invalid_transition'=>'That exception transition is not allowed.'],
];
