<?php
return [
 'title'=>'Apurements financiers des visites','empty'=>'Aucun dossier d’apurement financier trouvé.',
 'status'=>['pending'=>'En attente','cleared'=>'Apuré','conditionally_cleared'=>'Apuré sous condition','financially_closed'=>'Clôturé financièrement','stale'=>'Obsolète'],
 'basis'=>['fully_settled'=>'Entièrement réglé','zero_patient_responsibility'=>'Aucune part patient','fully_insured'=>'Entièrement assuré','fully_sponsored'=>'Entièrement sponsorisé','corporate_guarantee'=>'Garantie d’entreprise','insurance_pending_approved'=>'Assurance en attente approuvée','approved_outstanding_balance'=>'Solde impayé approuvé','approved_payment_plan'=>'Plan de paiement approuvé','management_approval'=>'Approbation de la direction'],
 'exception_type'=>['outstanding_balance_approval'=>'Approbation du solde impayé','payment_plan'=>'Plan de paiement','insurance_pending'=>'Assurance en attente','corporate_guarantee'=>'Garantie d’entreprise','management_approval'=>'Approbation de la direction'],
 'fields'=>['visit'=>'Visite','patient'=>'Patient','status'=>'Statut','basis'=>'Base','outstanding'=>'Solde patient','action_required'=>'Action financière requise','reason'=>'Motif','exceptions'=>'Exceptions','type'=>'Type','amount'=>'Montant'],
 'actions'=>['report'=>'Rapport','export'=>'Exporter','filter'=>'Filtrer','assess'=>'Évaluer','close'=>'Clôturer financièrement la visite','request_exception'=>'Demander un apurement conditionnel','request'=>'Demander','approve'=>'Approuver','save'=>'Enregistrer','rollback'=>'Revenir au mode désactivé'],
 'metrics'=>['pending'=>'En attente','cleared'=>'Apuré','conditional'=>'Apuré sous condition','closed'=>'Clôturé financièrement','stale'=>'Obsolète','outstanding'=>'Solde patient impayé'],
 'settings'=>['title'=>'Paramètres d’apurement financier','force_disabled'=>'La sécurité de l’environnement force la désactivation de l’apurement financier.','effective'=>'Mode effectif','confirm_activation'=>'Je confirme l’activation de la clôture financière'],
 'flash'=>['assessed'=>'Apurement financier évalué.','closed'=>'Visite clôturée financièrement.','reopened'=>'Apurement financier rouvert.','exception_requested'=>'Exception demandée.','exception_approved'=>'Exception approuvée.','settings_updated'=>'Paramètres mis à jour.','rolled_back'=>'Apurement financier remis en mode désactivé.'],
 'errors'=>['active_required'=>'La clôture financière est disponible uniquement en mode actif.','not_clear'=>'La visite n’est pas financièrement apurée.','pending_exists'=>'Une exception en attente existe déjà.','approved_exists'=>'Une exception approuvée actuelle existe déjà.','amount_exceeds_outstanding'=>'Le montant ne doit pas dépasser le solde patient actuel.','not_pending'=>'L’exception n’est plus en attente.','self_approval'=>'Le demandeur ne peut pas approuver sa propre exception.','invalid_transition'=>'Cette transition d’exception n’est pas autorisée.'],
];
