@extends('layouts.app')
@section('title', __('accounting.reconciliation_history'))
@section('content')
<x-page-header :title="__('accounting.reconciliation_history')" :description="__('accounting.reconciliation_history_description')" icon="ti-history" />
<div class="card mb-3"><div class="card-body"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">{{ __('accounting.reconciliation_type') }}</label><select class="form-select" name="type"><option value="">{{ __('common.all') }}</option>@foreach($types as $type)<option value="{{ $type }}" @selected(request('type') === $type)>{{ __('accounting.reconciliation_type_'.$type) }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ __('common.status') }}</label><select class="form-select" name="status"><option value="">{{ __('common.all') }}</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ __('accounting.reconciliation_status_'.$status) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">{{ __('common.filter') }}</button></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="{{ route('admin.accounting.subledger-reconciliation.history') }}">{{ __('accounting.clear') }}</a></div></form></div></div>
<div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>#</th><th>{{ __('accounting.reconciliation_type') }}</th><th>{{ __('accounting.period') }}</th><th>{{ __('accounting.availability') }}</th><th>{{ __('accounting.difference_amount') }}</th><th>{{ __('common.status') }}</th><th>{{ __('accounting.started_by') }}</th><th>{{ __('accounting.approved_by') }}</th><th></th></tr></thead><tbody>
@forelse($runs as $run)<tr><td>{{ $run->id }}</td><td>{{ __('accounting.reconciliation_type_'.$run->reconciliation_type) }}</td><td>{{ $run->period_start->format('d M Y') }} - {{ $run->period_end->format('d M Y') }}</td><td>{{ __('accounting.availability_'.$run->availability()) }}</td><td>{{ number_format((float)$run->difference_amount, 2) }}</td><td>{{ __('accounting.reconciliation_status_'.$run->status) }}</td><td>{{ $run->startedBy?->name ?? '-' }}</td><td>{{ $run->approvedBy?->name ?? '-' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.accounting.subledger-reconciliation.show', $run) }}"><i class="ti ti-eye"></i></a></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-4">{{ __('accounting.no_reconciliation_runs') }}</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3 d-flex justify-content-end">{{ $runs->links() }}</div>
@endsection
