<div class="card">
    <div class="card-header"><h5 class="card-title mb-0"><i class="ti ti-baby-carriage me-1"></i>{{ __('maternity.labor_episode') }}</h5></div>
    <div class="card-body">
        @if($antenatalVisit)
        <input type="hidden" name="antenatal_visit_id" value="{{ $antenatalVisit->id }}">
        @endif
        <div class="row g-3">
            <div class="col-md-3"><label class="form-label">{{ __('maternity.started_at') }}</label><input type="datetime-local" name="started_at" class="form-control" value="{{ old('started_at', optional($episode?->started_at)->format('Y-m-d\\TH:i') ?? now()->format('Y-m-d\\TH:i')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.labor_onset') }}</label><input type="datetime-local" name="labor_onset_at" class="form-control" value="{{ old('labor_onset_at', optional($episode?->labor_onset_at)->format('Y-m-d\\TH:i')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.labor_stage') }}</label><select name="labor_stage" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($stages as $stage)<option value="{{ $stage->value }}" @selected(old('labor_stage', $episode?->labor_stage?->value ?? 'unknown') === $stage->value)>{{ $stage->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.labor_status') }}</label><select name="status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $episode?->status?->value ?? 'active') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>

            <div class="col-md-3"><label class="form-label">{{ __('maternity.related_case') }}</label><select name="maternity_case_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($maternityCases as $case)<option value="{{ $case->id }}" @selected(old('maternity_case_id', $episode?->maternity_case_id ?? $antenatalVisit?->maternity_case_id) == $case->id)>{{ $case->case_type?->label() }} #{{ $case->id }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.anc_visit') }}</label><select name="antenatal_visit_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($antenatalVisits as $visit)<option value="{{ $visit->id }}" @selected(old('antenatal_visit_id', $episode?->antenatal_visit_id ?? $antenatalVisit?->id) == $visit->id)>{{ $visit->visit_date?->format('d M Y') }} {{ $visit->gestational_age_weeks !== null ? '('.$visit->gestational_age_weeks.'w)' : '' }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.department') }}</label><select name="department_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $episode?->department_id ?? $profile->department_id) == $department->id)>{{ $department->name }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.delivery_mode_planned') }}</label><select name="delivery_mode_planned" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($deliveryModes as $mode)<option value="{{ $mode->value }}" @selected(old('delivery_mode_planned', $episode?->delivery_mode_planned?->value) === $mode->value)>{{ $mode->label() }}</option>@endforeach</select></div>

            <div class="col-md-3"><label class="form-label">{{ __('maternity.membranes_status') }}</label><select name="membranes_status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($membranesStatuses as $status)<option value="{{ $status->value }}" @selected(old('membranes_status', $episode?->membranes_status?->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.rupture_of_membranes') }}</label><input type="datetime-local" name="rupture_of_membranes_at" class="form-control" value="{{ old('rupture_of_membranes_at', optional($episode?->rupture_of_membranes_at)->format('Y-m-d\\TH:i')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.liquor_colour') }}</label><select name="liquor_colour" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($liquorColours as $colour)<option value="{{ $colour->value }}" @selected(old('liquor_colour', $episode?->liquor_colour?->value) === $colour->value)>{{ $colour->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.contractions_started_at') }}</label><input type="datetime-local" name="contractions_started_at" class="form-control" value="{{ old('contractions_started_at', optional($episode?->contractions_started_at)->format('Y-m-d\\TH:i')) }}"></div>

            <div class="col-md-4"><label class="form-label">{{ __('maternity.presentation') }}</label><input name="presentation" class="form-control" value="{{ old('presentation', $episode?->presentation ?? $antenatalVisit?->presentation?->value) }}"></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.fetal_position') }}</label><input name="fetal_position" class="form-control" value="{{ old('fetal_position', $episode?->fetal_position) }}"></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.referral_source') }}</label><input name="referral_source" class="form-control" value="{{ old('referral_source', $episode?->referral_source) }}"></div>

            <div class="col-md-6"><label class="form-label">{{ __('maternity.initial_assessment') }}</label><textarea name="initial_assessment" rows="4" class="form-control">{{ old('initial_assessment', $episode?->initial_assessment ?? $antenatalVisit?->assessment) }}</textarea></div>
            <div class="col-md-6"><label class="form-label">{{ __('maternity.clinical_summary') }}</label><textarea name="clinical_summary" rows="4" class="form-control">{{ old('clinical_summary', $episode?->clinical_summary ?? $antenatalVisit?->plan) }}</textarea></div>
        </div>
    </div>
    <div class="card-footer text-end"><a href="{{ route('admin.maternity.pregnancies.show', $profile) }}" class="btn btn-outline-secondary">{{ __('common.cancel') }}</a><button class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i>{{ __('common.save') }}</button></div>
</div>
