<?php

return [
    'setup_country_code' => strtoupper(env('APP_COUNTRY_CODE', 'GH')),

    'countries' => [
        'GH' => [
            'name' => 'Ghana',
            'iso2' => 'GH',
            'dial_code' => '+233',
            'phone_placeholder' => '0241234567',
            'phone_pattern' => '(\\+233|0)[235][0-9]{8}',
            'phone_regex' => '/^(?:\\+233|0)[235][0-9]{8}$/',
            'digital_address_pattern' => '[A-Z]{2}-[0-9]{3,4}-[0-9]{3,4}',
            'digital_address_regex' => '/^[A-Z]{2}-[0-9]{3,4}-[0-9]{3,4}$/',
            'digital_address_placeholder' => 'GA-123-4567',
        ],
        'TG' => [
            'name' => 'Togo',
            'iso2' => 'TG',
            'dial_code' => '+228',
            'phone_placeholder' => '+22890123456',
            'phone_pattern' => '\\+228[0-9]{8}',
            'phone_regex' => '/^\\+228[0-9]{8}$/',
            'digital_address_pattern' => null,
            'digital_address_regex' => null,
            'digital_address_placeholder' => null,
        ],
    ],

    'occupations' => [
        'Accountant',
        'Architect',
        'Artist',
        'Baker',
        'Banker',
        'Barber',
        'Business Owner',
        'Carpenter',
        'Cashier',
        'Chef',
        'Civil Servant',
        'Clergy',
        'Cleaner',
        'Construction Worker',
        'Consultant',
        'Dentist',
        'Doctor',
        'Driver',
        'Electrician',
        'Engineer',
        'Farmer',
        'Fisherman',
        'Graphic Designer',
        'Hairdresser',
        'Journalist',
        'Lawyer',
        'Lecturer',
        'Mechanic',
        'Miner',
        'Musician',
        'Nurse',
        'Pharmacist',
        'Photographer',
        'Pilot',
        'Plumber',
        'Police Officer',
        'Politician',
        'Programmer',
        'Retired',
        'Salesperson',
        'Secretary',
        'Security Guard',
        'Social Worker',
        'Student',
        'Surveyor',
        'Tailor',
        'Teacher',
        'Technician',
        'Trader',
        'Unemployed',
        'Veterinarian',
        'Welder',
        'Other',
    ],
];
