<div class="card">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-4"><label class="form-label">{{ __('maternity.patient') }}</label><select name="patient_id" class="form-select" required><option value="">{{ __('maternity.select_patient') }}</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(old('patient_id', $profile?->patient_id) == $patient->id)>{{ $patient->full_name }} - {{ $patient->patient_number }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.linked_visit') }}</label><select name="visit_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($visits as $visit)<option value="{{ $visit->id }}" @selected(old('visit_id', $profile?->visit_id) == $visit->id)>{{ $visit->visit_number }} - {{ $visit->patient?->full_name }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.linked_admission') }}</label><select name="admission_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($admissions as $admission)<option value="{{ $admission->id }}" @selected(old('admission_id', $profile?->admission_id) == $admission->id)>{{ $admission->admission_number }} - {{ $admission->patient?->full_name }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.department') }}</label><select name="department_id" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $profile?->department_id) == $department->id)>{{ $department->name }}</option>@endforeach</select></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.gravida') }}</label><input type="number" min="0" max="30" name="gravida" class="form-control" value="{{ old('gravida', $profile?->gravida) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.para') }}</label><input type="number" min="0" max="30" name="para" class="form-control" value="{{ old('para', $profile?->para) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.abortions') }}</label><input type="number" min="0" max="30" name="abortions" class="form-control" value="{{ old('abortions', $profile?->abortions) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.living_children') }}</label><input type="number" min="0" max="30" name="living_children" class="form-control" value="{{ old('living_children', $profile?->living_children) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.lmp') }}</label><input type="date" name="last_menstrual_period" class="form-control" value="{{ old('last_menstrual_period', $profile?->last_menstrual_period?->format('Y-m-d')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.edd') }}</label><input type="date" name="estimated_due_date" class="form-control" value="{{ old('estimated_due_date', $profile?->estimated_due_date?->format('Y-m-d')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.blood_group') }}</label><select name="blood_group" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($bloodGroups as $group)<option value="{{ $group->value }}" @selected(old('blood_group', $profile?->blood_group) === $group->value)>{{ $group->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.rhesus_status') }}</label><select name="rhesus_status" class="form-select"><option value="unknown">{{ __('maternity.unknown') }}</option><option value="positive" @selected(old('rhesus_status', $profile?->rhesus_status) === 'positive')>{{ __('maternity.positive') }}</option><option value="negative" @selected(old('rhesus_status', $profile?->rhesus_status) === 'negative')>{{ __('maternity.negative') }}</option></select></div>
            <div class="col-12"><label class="form-label">{{ __('maternity.known_risks') }}</label><textarea name="known_risks" rows="3" class="form-control">{{ old('known_risks', collect($profile?->known_risks ?? [])->implode("\n")) }}</textarea></div>
            <div class="col-12"><label class="form-label">{{ __('maternity.allergies_snapshot') }}</label><textarea name="allergies_snapshot" rows="2" class="form-control">{{ old('allergies_snapshot', $profile?->allergies_snapshot) }}</textarea></div>
            @foreach(['previous_caesarean','previous_postpartum_haemorrhage','hypertensive_disorder_risk','diabetes_risk','multiple_pregnancy'] as $flag)
            <div class="col-md-4"><div class="form-check"><input type="hidden" name="{{ $flag }}" value="0"><input class="form-check-input" type="checkbox" name="{{ $flag }}" value="1" id="{{ $flag }}" @checked(old($flag, $profile?->{$flag}) )><label class="form-check-label" for="{{ $flag }}">{{ __('maternity.'.$flag) }}</label></div></div>
            @endforeach
        </div>
    </div>
    <div class="card-footer text-end"><a href="{{ route('admin.maternity.pregnancies.index') }}" class="btn btn-outline-secondary">{{ __('common.cancel') }}</a><button class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i>{{ __('common.save') }}</button></div>
</div>
