@php
    $selectedRiskFlags = old('risk_flags', $record?->risk_flags ?? []);
    $selectedDangerSigns = old('danger_signs', $record?->danger_signs ?? []);
@endphp
<div class="card">
    <div class="card-header"><h5 class="card-title mb-0"><i class="ti ti-baby-bottle me-1"></i>{{ __('maternity.newborn_record') }}</h5></div>
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-2"><label class="form-label">{{ __('maternity.baby_number') }}</label><input type="number" min="1" name="baby_number" class="form-control" value="{{ old('baby_number', $record?->baby_number ?? ($delivery->newbornRecords()->max('birth_order') + 1)) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.birth_order') }}</label><input type="number" min="1" name="birth_order" class="form-control" value="{{ old('birth_order', $record?->birth_order ?? ($delivery->newbornRecords()->max('birth_order') + 1)) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.sex') }}</label><select name="sex" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($sexes as $sex)<option value="{{ $sex->value }}" @selected(old('sex', $record?->sex?->value) === $sex->value)>{{ $sex->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.birth_time') }}</label><input type="datetime-local" name="birth_time" class="form-control" value="{{ old('birth_time', optional($record?->birth_time ?? $delivery->delivery_at)->format('Y-m-d\\TH:i')) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.newborn_outcome') }}</label><select name="outcome" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($outcomes as $outcome)<option value="{{ $outcome->value }}" @selected(old('outcome', $record?->outcome?->value ?? 'live_birth') === $outcome->value)>{{ $outcome->label() }}</option>@endforeach</select></div>

            <div class="col-md-3"><label class="form-label">{{ __('maternity.birth_weight') }}</label><input type="number" step="0.001" name="birth_weight_kg" class="form-control" value="{{ old('birth_weight_kg', $record?->birth_weight_kg) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.length') }}</label><input type="number" step="0.01" name="length_cm" class="form-control" value="{{ old('length_cm', $record?->length_cm) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.head_circumference') }}</label><input type="number" step="0.01" name="head_circumference_cm" class="form-control" value="{{ old('head_circumference_cm', $record?->head_circumference_cm) }}"></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.newborn_status') }}</label><select name="status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $record?->status?->value ?? 'active') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>

            <div class="col-md-2"><label class="form-label">{{ __('maternity.apgar_1_min') }}</label><input type="number" min="0" max="10" name="apgar_1_min" class="form-control" value="{{ old('apgar_1_min', $record?->apgar_1_min) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.apgar_5_min') }}</label><input type="number" min="0" max="10" name="apgar_5_min" class="form-control" value="{{ old('apgar_5_min', $record?->apgar_5_min) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.apgar_10_min') }}</label><input type="number" min="0" max="10" name="apgar_10_min" class="form-control" value="{{ old('apgar_10_min', $record?->apgar_10_min) }}"></div>
            <div class="col-md-2"><label class="form-label">{{ __('maternity.temperature') }}</label><input type="number" step="0.1" name="temperature" class="form-control" value="{{ old('temperature', $record?->temperature) }}"></div>
            <div class="col-md-4"><label class="form-label">{{ __('maternity.neonatal_condition') }}</label><select name="neonatal_condition" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($conditions as $condition)<option value="{{ $condition->value }}" @selected(old('neonatal_condition', $record?->neonatal_condition?->value) === $condition->value)>{{ $condition->label() }}</option>@endforeach</select></div>

            <div class="col-md-3"><label class="form-label">{{ __('maternity.cried_at_birth') }}</label><select name="cried_at_birth" class="form-select"><option value="">{{ __('common.none') }}</option><option value="1" @selected(old('cried_at_birth', $record?->cried_at_birth) === true || old('cried_at_birth') === '1')>{{ __('common.yes') }}</option><option value="0" @selected(old('cried_at_birth', $record?->cried_at_birth) === false || old('cried_at_birth') === '0')>{{ __('common.no') }}</option></select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.resuscitation_required') }}</label><select name="resuscitation_required" class="form-select"><option value="0" @selected(! old('resuscitation_required', $record?->resuscitation_required ?? false))>{{ __('common.no') }}</option><option value="1" @selected(old('resuscitation_required', $record?->resuscitation_required) === true || old('resuscitation_required') === '1')>{{ __('common.yes') }}</option></select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.feeding_status') }}</label><select name="feeding_status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($feedingStatuses as $status)<option value="{{ $status->value }}" @selected(old('feeding_status', $record?->feeding_status?->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.breathing_status') }}</label><select name="breathing_status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($breathingStatuses as $status)<option value="{{ $status->value }}" @selected(old('breathing_status', $record?->breathing_status?->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>

            <div class="col-md-3"><label class="form-label">{{ __('maternity.cord_status') }}</label><select name="cord_status" class="form-select"><option value="">{{ __('common.none') }}</option>@foreach($cordStatuses as $status)<option value="{{ $status->value }}" @selected(old('cord_status', $record?->cord_status?->value) === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
            <div class="col-md-3"><label class="form-label">{{ __('maternity.colour') }}</label><input name="colour" class="form-control" value="{{ old('colour', $record?->colour) }}"></div>
            <div class="col-md-6"><label class="form-label">{{ __('maternity.transferred_to') }}</label><input name="transferred_to" class="form-control" value="{{ old('transferred_to', $record?->transferred_to) }}"></div>

            <div class="col-md-6"><label class="form-label">{{ __('maternity.resuscitation_details') }}</label><textarea name="resuscitation_details" rows="3" class="form-control">{{ old('resuscitation_details', $record?->resuscitation_details) }}</textarea></div>
            <div class="col-md-6"><label class="form-label">{{ __('maternity.congenital_concerns') }}</label><textarea name="congenital_concerns" rows="3" class="form-control">{{ old('congenital_concerns', $record?->congenital_concerns) }}</textarea></div>

            <div class="col-md-6"><label class="form-label">{{ __('maternity.risk_flags') }}</label><div class="border rounded p-2" style="max-height:220px;overflow:auto;">@foreach($riskFlags as $flag)<div class="form-check"><input class="form-check-input" type="checkbox" name="risk_flags[]" value="{{ $flag->value }}" id="newborn_risk_{{ $flag->value }}" @checked(in_array($flag->value, $selectedRiskFlags, true))><label class="form-check-label" for="newborn_risk_{{ $flag->value }}">{{ $flag->label() }}</label></div>@endforeach</div></div>
            <div class="col-md-6"><label class="form-label">{{ __('maternity.danger_signs') }}</label><div class="border rounded p-2" style="max-height:220px;overflow:auto;">@foreach($dangerSigns as $sign)<div class="form-check"><input class="form-check-input" type="checkbox" name="danger_signs[]" value="{{ $sign->value }}" id="newborn_danger_{{ $sign->value }}" @checked(in_array($sign->value, $selectedDangerSigns, true))><label class="form-check-label" for="newborn_danger_{{ $sign->value }}">{{ $sign->label() }}</label></div>@endforeach</div></div>

            <div class="col-12"><label class="form-label">{{ __('maternity.notes') }}</label><textarea name="notes" rows="3" class="form-control">{{ old('notes', $record?->notes) }}</textarea></div>
        </div>
    </div>
    <div class="card-footer text-end"><a href="{{ route('admin.maternity.deliveries.show', $delivery) }}" class="btn btn-outline-secondary">{{ __('common.cancel') }}</a><button class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i>{{ __('common.save') }}</button></div>
</div>
