@extends('layouts.app')
@section('title', __('visit_financial_clearance.title'))
@section('content')
<div class="container-fluid">
 <div class="d-flex justify-content-between align-items-center mb-3"><h4>{{ __('visit_financial_clearance.title') }}</h4><div><a class="btn btn-outline-secondary" href="{{ route('admin.billing.visit-financial-clearances.report') }}">{{ __('visit_financial_clearance.actions.report') }}</a> <a class="btn btn-outline-secondary" href="{{ route('admin.billing.visit-financial-clearances.export') }}">{{ __('visit_financial_clearance.actions.export') }}</a></div></div>
 <form class="card card-body mb-3" method="GET"><div class="row g-2"><div class="col"><input class="form-control" name="status" value="{{ request('status') }}" placeholder="{{ __('visit_financial_clearance.fields.status') }}"></div><div class="col"><input class="form-control" name="basis" value="{{ request('basis') }}" placeholder="{{ __('visit_financial_clearance.fields.basis') }}"></div><div class="col"><label><input type="checkbox" name="requires_finance_action" value="1" @checked(request('requires_finance_action'))> {{ __('visit_financial_clearance.fields.action_required') }}</label></div><div class="col"><button class="btn btn-primary">{{ __('visit_financial_clearance.actions.filter') }}</button></div></div></form>
 <div class="card"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('visit_financial_clearance.fields.visit') }}</th><th>{{ __('visit_financial_clearance.fields.patient') }}</th><th>{{ __('visit_financial_clearance.fields.status') }}</th><th>{{ __('visit_financial_clearance.fields.basis') }}</th><th class="text-end">{{ __('visit_financial_clearance.fields.outstanding') }}</th></tr></thead><tbody>@forelse($clearances as $c)<tr><td><a href="{{ route('admin.billing.visit-financial-clearances.show', $c->visit) }}">{{ $c->visit?->visit_number }}</a></td><td>{{ $c->visit?->patient?->full_name }}</td><td>{{ __('visit_financial_clearance.status.'.$c->status->value) }}</td><td>{{ $c->basis ? __('visit_financial_clearance.basis.'.$c->basis->value) : '—' }}</td><td class="text-end">{{ number_format($c->patient_outstanding_snapshot, 2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">{{ __('visit_financial_clearance.empty') }}</td></tr>@endforelse</tbody></table></div></div>
 {{ $clearances->links() }}
</div>
@endsection
