@extends('layouts.app')
@section('title', __('visit_financial_clearance.title'))
@section('content')
<div class="container-fluid"><h4>{{ $visit->visit_number }} — {{ __('visit_financial_clearance.title') }}</h4>
<div class="card card-body mb-3">@if($clearance)<div class="row"><div class="col"><strong>{{ __('visit_financial_clearance.fields.status') }}:</strong> {{ __('visit_financial_clearance.status.'.$clearance->status->value) }}</div><div class="col"><strong>{{ __('visit_financial_clearance.fields.basis') }}:</strong> {{ $clearance->basis?->value ?? '—' }}</div><div class="col"><strong>{{ __('visit_financial_clearance.fields.outstanding') }}:</strong> {{ number_format($clearance->patient_outstanding_snapshot, 2) }}</div></div>@else<p>{{ __('visit_financial_clearance.empty') }}</p>@endif
<div class="mt-3 d-flex gap-2">@can('visits.financial_clearance.assess')<form method="POST" action="{{ route('admin.billing.visit-financial-clearances.assess', $visit) }}">@csrf<button class="btn btn-primary">{{ __('visit_financial_clearance.actions.assess') }}</button></form>@endcan @can('visits.financial_clearance.close')<form method="POST" action="{{ route('admin.billing.visit-financial-clearances.close', $visit) }}">@csrf<input name="reason" required maxlength="500" placeholder="{{ __('visit_financial_clearance.fields.reason') }}"><button class="btn btn-success">{{ __('visit_financial_clearance.actions.close') }}</button></form>@endcan</div></div>
@can('visits.financial_clearance_exception.request')<div class="card card-body mb-3"><h5>{{ __('visit_financial_clearance.actions.request_exception') }}</h5><form method="POST" action="{{ route('admin.billing.visit-financial-clearances.exceptions.request', $visit) }}">@csrf<div class="row g-2"><div class="col"><select class="form-select" name="type">@foreach(\App\Enums\VisitFinancialClearanceExceptionType::cases() as $type)<option value="{{ $type->value }}">{{ __('visit_financial_clearance.exception_type.'.$type->value) }}</option>@endforeach</select></div><div class="col"><input class="form-control" type="number" step="0.01" name="requested_amount" required></div><div class="col"><input class="form-control" name="request_reason" required maxlength="1000" placeholder="{{ __('visit_financial_clearance.fields.reason') }}"></div><div class="col"><button class="btn btn-warning">{{ __('visit_financial_clearance.actions.request') }}</button></div></div></form></div>@endcan
<div class="card"><div class="card-header">{{ __('visit_financial_clearance.fields.exceptions') }}</div><div class="table-responsive"><table class="table"><tr><th>{{ __('visit_financial_clearance.fields.type') }}</th><th>{{ __('visit_financial_clearance.fields.status') }}</th><th>{{ __('visit_financial_clearance.fields.amount') }}</th><th></th></tr>@foreach($exceptions as $e)<tr><td>{{ $e->type->value }}</td><td>{{ $e->status->value }}</td><td>{{ $e->approved_amount ?? $e->requested_amount }}</td><td>@if($e->status === \App\Enums\VisitFinancialClearanceExceptionStatus::PENDING) @can('visits.financial_clearance_exception.approve')<form method="POST" action="{{ route('admin.billing.visit-financial-clearances.exceptions.approve', $e) }}">@csrf<input type="hidden" name="approved_amount" value="{{ $e->requested_amount }}"><input name="reason" required placeholder="{{ __('visit_financial_clearance.fields.reason') }}"><button class="btn btn-sm btn-success">{{ __('visit_financial_clearance.actions.approve') }}</button></form>@endcan @endif</td></tr>@endforeach</table></div></div>
</div>
@endsection
