<?php

namespace App\Http\Controllers\Admin\Dashboard;

use App\Http\Controllers\Controller;
use App\Support\PermissionMeta;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Read-only admin dashboard for the global permission catalogue.
 *
 * Backed by `storage/reports/permissions_audit.json` (regenerated by
 * `php artisan permissions:audit --json`, run by the scheduler nightly).
 */
class PermissionDashboardController extends Controller
{
    public function index(Request $request)
    {
        // Ensure the report exists; regenerate inline if missing.
        $reportPath = storage_path('reports/permissions_audit.json');
        if (! file_exists($reportPath)) {
            Artisan::call('permissions:audit', ['--json' => true]);
        }

        $report = json_decode((string) @file_get_contents($reportPath), true) ?: [];

        // Build the catalogue table — group by module, decorated with risk.
        $catalogue = Permission::orderBy('name')->get()
            ->map(function ($p) {
                return [
                    'id'          => $p->id,
                    'name'        => $p->name,
                    'module'      => PermissionMeta::module($p->name),
                    'description' => PermissionMeta::description($p->name),
                    'risk'        => PermissionMeta::risk($p->name),
                ];
            })
            ->groupBy('module')
            ->sortKeys();

        $riskLevels = config('permissions.risk_levels', []);

        return view('admin.permissions.index', compact('report', 'catalogue', 'riskLevels'));
    }

    /**
     * Trigger a fresh audit on demand. Used by the "Refresh" button.
     */
    public function refresh()
    {
        Artisan::call('permissions:audit', ['--json' => true]);
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        return redirect()->route('admin.permissions.index')
            ->with('success', __('messages.permissions.audit_refreshed'));
    }
}
